### ISSUE TITLE
Cannot  Use

### ISSUE THREAD

**Issue by kokawa2003** [cloudnative-co/python-zoom-sdk#1]
I cannot run this code
```python
import Zoom
import json

cli=Zoom.Client(api_key="XXXX",api_secret="XXXX")

print(cli)
USER_ID = "XXXX"
CREATE_MEETING_URL = "https://api.zoom.us/v2/users/" + USER_ID + "/meetings"
print(CREATE_MEETING_URL)
mydict = {"type":1}

cli.request(method="POST",path=CREATE_MEETING_URL,payload=mydict,to_dict=True)
```
This is exception:
Traceback (most recent call last):
  File "test2.py", line 12, in <module>
    cli.request(method="POST",path=CREATE_MEETING_URL,payload=mydict,to_dict=True)
  File "C:\Users\oakoa\work\zoomtest\venv\lib\site-packages\zoomsdk-0.0.1-py3.8.egg\Zoom\client.py", line 77, in request
  File "C:\Users\oakoa\work\zoomtest\venv\lib\site-packages\zoomsdk-0.0.1-py3.8.egg\Zoom\Exception\__init__.py", line 15, in __init__
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please tell me how to solve this

**Comment by Hirose-Sebastian-Taikai** [comment]
If you want to access user information, you should use a Users class that extends Client.
And then there's the Meeting class.
I have only implemented the API that I needed for my use, so improvements are welcome!
If you use the request directly in the Client, you should specify a relative path as the path argument

もしユーザー情報にアクセスするならClientを継承したUsersクラスを使用して欲しいです。
それとMeetingクラスもあります
私は私の用途の為に必要だったAPIしか実装していないので改修は大歓迎です

Clientを直接使うならpathは相対パスの指定になります。

```
import Zoom
client=Zoom.Client(api_key="XXXX",api_secret="XXXX")
client.request(method="POST",path="/users",payload=mydict,to_dict=True)
```

**Comment by kokawa2003** [comment]
My re-new code is this. working well thank you.
import Zoom
import json

cli=Zoom.Client(api_key="XXXX",api_secret="XXX")

print(cli)
USER_ID = "XXXXXXXXXXX"
CREATE_MEETING_URL = "/users/" + USER_ID + "/meetings"
print(CREATE_MEETING_URL)
mydict = {"type":1}

cli.request(method="POST",path=CREATE_MEETING_URL,payload=mydict,to_dict=True)

で、ここから先はちょっとこの話とは別件になるので株式会社クラウドネイティブにメールさせてください。
